---
name: C

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build with GCC
    runs-on: ubuntu-latest
    steps:
      - name: Set REPOSITORY
        shell: bash
        run: echo "REPOSITORY=${GITHUB_REPOSITORY#*/}" >> "${GITHUB_ENV}"
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set SOURCE_DATE_EPOCH
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "${GITHUB_ENV}"
      - name: Install clang-tidy
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install clang-tidy
      - name: Run clang-tidy
        shell: bash
        run: clang-tidy *.c
      - name: Build
        shell: bash
        run: make all
      - name: Upload artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: ${{ env.REPOSITORY }}
          path: bin/
