name: C

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Run clang-tidy
      run: clang-tidy *.c
    - name: Build
      run: make all
