---
name: C

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:

  build:
    name: Build with GCC
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Install clang-tidy
      run: |
        sudo apt update -y
        sudo apt install clang-tidy
    - name: Run clang-tidy
      run: clang-tidy *.c
    - name: Build
      run: make all
