name: C

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    # run only on internal PRs, external ones already run on push.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install clang-tidy
      run: |
        sudo apt update -y
        sudo apt install clang-tidy
    - name: Run clang-tidy
      run: clang-tidy *.c
    - name: Build
      run: make all
