---
name: C

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:

  build:
    name: Build with GCC
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Install clang-tidy
      run: |
        sudo apt update -y
        sudo apt install clang-tidy
    - name: Run clang-tidy
      run: clang-tidy *.c
    - name: Build
      run: make all
